# .github/workflows/jekyll-build.yml

name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    # Add this permissions block:
    permissions:
      contents: write # Allows the bot to write to the repository (for _site)
      pages: write    # Grants permission to manage GitHub Pages deployments
      id-token: write # Required for OpenID Connect (OIDC) authentication, good practice

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --trace

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: master
          force_orphan: true