# .github/workflows/jekyll-build.yml

name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main # Trigger this workflow on pushes to your 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Use a standard Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your code

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Important: Use a Ruby version that matches your local setup (e.g., 3.2 or 3.3).
                              # You are using 3.2.8 locally, so '3.2' is a good match.
          bundler-cache: true # Installs dependencies with Bundler (from your Gemfile.lock)

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --trace # Build the site with your gems. --trace helps with debugging.

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Recommended action for deploying static sites
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site # The directory where Jekyll outputs the built site
          # The 'publish_branch' must match the branch you configured for GitHub Pages to serve from.
          # For username.github.io repos, it's usually 'main'.
          publish_branch: main # <--- CONFIRM THIS MATCHES YOUR GITHUB PAGES SETTINGS
          force_orphan: true # Recommended for clean deployments, overwrites history of publish_branch
